# -*- coding: utf-8 -*-
"""hellow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1atPvWx0VYdFueqrGblltIaXkiX9sTEOO
"""

import numpy as np

print("Hello world! This is PHY277's version of it")